### ISSUE TITLE
doesn't allow click through on markdown links

### ISSUE THREAD

**Issue by capaj** [ewnd9/hyperclick-markdown#1]
Markdown has links like this:

```
[A link](reddit.com)
```

Would be nice if I could click on reddit.com and get to it.

**Comment by ewnd9** [comment]
Thanks for the bug report :tada:

**Comment by FlorianWendelborn** [comment]
Looking at the code, I think this breaks for domains that don't include a dot, like `localhost`.

**Comment by ewnd9** [comment]
@dodekeract Are there any other domains besides `localhost`? I can only imagine adding a check like `str.indexOf('localhost') === 0` right now. What do you think?

**Comment by FlorianWendelborn** [comment]
Natively, not that I'm aware of, however some people (including me) have custom entries in their DNS or hostfile, so every domain is possible. I'm not sure what a better way to detect it would be.

(For example, my server is literally reachable at `ssh dodekeract@server` on my devices)

**Comment by ewnd9** [comment]
I'm up for `localhost` (I definitely use links to server development addresses like `localhost:8080` in docs)  but custom domains look too vague (Don't want to highlight every single word to support this or to have many conditions in code)
